# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Mar 26 01:00:42 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1341, 939)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.btnLoadTst = QtGui.QPushButton(self.centralWidget)
        self.btnLoadTst.setGeometry(QtCore.QRect(20, 50, 171, 31))
        self.btnLoadTst.setObjectName(_fromUtf8("btnLoadTst"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 10, 211, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioOrigin = QtGui.QRadioButton(self.groupBox)
        self.radioOrigin.setGeometry(QtCore.QRect(10, 30, 110, 41))
        self.radioOrigin.setChecked(True)
        self.radioOrigin.setObjectName(_fromUtf8("radioOrigin"))
        self.radioGeometric = QtGui.QRadioButton(self.groupBox)
        self.radioGeometric.setGeometry(QtCore.QRect(10, 70, 181, 26))
        self.radioGeometric.setObjectName(_fromUtf8("radioGeometric"))
        self.btnLoadPlacement = QtGui.QPushButton(self.centralWidget)
        self.btnLoadPlacement.setGeometry(QtCore.QRect(20, 10, 171, 31))
        self.btnLoadPlacement.setObjectName(_fromUtf8("btnLoadPlacement"))
        self.btnLoadCCD = QtGui.QPushButton(self.centralWidget)
        self.btnLoadCCD.setGeometry(QtCore.QRect(20, 90, 171, 31))
        self.btnLoadCCD.setObjectName(_fromUtf8("btnLoadCCD"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(10, 130, 1071, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.comboBox = QtGui.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 90, 83, 29))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.dial = QtGui.QDial(self.centralWidget)
        self.dial.setGeometry(QtCore.QRect(470, 70, 50, 64))
        self.dial.setObjectName(_fromUtf8("dial"))
        self.lblAbout = QtGui.QLabel(self.centralWidget)
        self.lblAbout.setGeometry(QtCore.QRect(830, 20, 181, 31))
        self.lblAbout.setObjectName(_fromUtf8("lblAbout"))
        self.lblStatus = QtGui.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(810, 100, 441, 21))
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(750, 100, 51, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtPort = QtGui.QLineEdit(self.centralWidget)
        self.txtPort.setGeometry(QtCore.QRect(610, 10, 113, 33))
        self.txtPort.setObjectName(_fromUtf8("txtPort"))
        self.btnConnect = QtGui.QPushButton(self.centralWidget)
        self.btnConnect.setGeometry(QtCore.QRect(510, 10, 95, 31))
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.lblMachineStatus = QtGui.QLabel(self.centralWidget)
        self.lblMachineStatus.setGeometry(QtCore.QRect(520, 50, 201, 21))
        self.lblMachineStatus.setObjectName(_fromUtf8("lblMachineStatus"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 150, 511, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_2 = QtGui.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_6)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 481, 221))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setColumnCount(8)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setHighlightSections(False)
        self.label_3 = QtGui.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 181, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.treePackages = QtGui.QTreeWidget(self.tab_6)
        self.treePackages.setGeometry(QtCore.QRect(10, 290, 481, 191))
        self.treePackages.setAlternatingRowColors(True)
        self.treePackages.setObjectName(_fromUtf8("treePackages"))
        self.treePackages.headerItem().setText(0, _fromUtf8("1"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.btnBoardM1 = QtGui.QPushButton(self.tab)
        self.btnBoardM1.setGeometry(QtCore.QRect(10, 20, 95, 31))
        self.btnBoardM1.setObjectName(_fromUtf8("btnBoardM1"))
        self.btnBoardM2 = QtGui.QPushButton(self.tab)
        self.btnBoardM2.setGeometry(QtCore.QRect(110, 20, 121, 31))
        self.btnBoardM2.setObjectName(_fromUtf8("btnBoardM2"))
        self.btnBoardM3 = QtGui.QPushButton(self.tab)
        self.btnBoardM3.setGeometry(QtCore.QRect(240, 20, 121, 31))
        self.btnBoardM3.setObjectName(_fromUtf8("btnBoardM3"))
        self.btnClearAlignment = QtGui.QPushButton(self.tab)
        self.btnClearAlignment.setGeometry(QtCore.QRect(370, 20, 131, 31))
        self.btnClearAlignment.setObjectName(_fromUtf8("btnClearAlignment"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 60, 67, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btnAlign = QtGui.QPushButton(self.tab)
        self.btnAlign.setGeometry(QtCore.QRect(40, 110, 111, 31))
        self.btnAlign.setObjectName(_fromUtf8("btnAlign"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 160, 131, 77))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblO1 = QtGui.QLabel(self.layoutWidget)
        self.lblO1.setObjectName(_fromUtf8("lblO1"))
        self.verticalLayout.addWidget(self.lblO1)
        self.lblO2 = QtGui.QLabel(self.layoutWidget)
        self.lblO2.setObjectName(_fromUtf8("lblO2"))
        self.verticalLayout.addWidget(self.lblO2)
        self.lblO3 = QtGui.QLabel(self.layoutWidget)
        self.lblO3.setObjectName(_fromUtf8("lblO3"))
        self.verticalLayout.addWidget(self.lblO3)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 160, 121, 77))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblP1 = QtGui.QLabel(self.layoutWidget1)
        self.lblP1.setObjectName(_fromUtf8("lblP1"))
        self.verticalLayout_2.addWidget(self.lblP1)
        self.lblP2 = QtGui.QLabel(self.layoutWidget1)
        self.lblP2.setObjectName(_fromUtf8("lblP2"))
        self.verticalLayout_2.addWidget(self.lblP2)
        self.lblP3 = QtGui.QLabel(self.layoutWidget1)
        self.lblP3.setObjectName(_fromUtf8("lblP3"))
        self.verticalLayout_2.addWidget(self.lblP3)
        self.lblBoardStatus = QtGui.QLabel(self.tab)
        self.lblBoardStatus.setGeometry(QtCore.QRect(90, 60, 441, 21))
        self.lblBoardStatus.setObjectName(_fromUtf8("lblBoardStatus"))
        self.imgFiduc1 = QtGui.QLabel(self.tab)
        self.imgFiduc1.setGeometry(QtCore.QRect(30, 250, 100, 100))
        self.imgFiduc1.setFrameShape(QtGui.QFrame.Box)
        self.imgFiduc1.setObjectName(_fromUtf8("imgFiduc1"))
        self.imgFiduc2 = QtGui.QLabel(self.tab)
        self.imgFiduc2.setGeometry(QtCore.QRect(150, 250, 100, 100))
        self.imgFiduc2.setFrameShape(QtGui.QFrame.Box)
        self.imgFiduc2.setObjectName(_fromUtf8("imgFiduc2"))
        self.imgFiduc3 = QtGui.QLabel(self.tab)
        self.imgFiduc3.setGeometry(QtCore.QRect(270, 250, 100, 100))
        self.imgFiduc3.setFrameShape(QtGui.QFrame.Box)
        self.imgFiduc3.setObjectName(_fromUtf8("imgFiduc3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 70, 171, 151))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox#groupBox_2 { \n"
"     border: 2px solid gray; \n"
"     border-radius: 3px; \n"
" }\n"
"QGroupBox::title { \n"
"    background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:0 10px;\n"
"     border: 2px solid gray; \n"
" } "))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 21, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 21, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtBoardY = QtGui.QLineEdit(self.groupBox_2)
        self.txtBoardY.setGeometry(QtCore.QRect(40, 70, 113, 33))
        self.txtBoardY.setObjectName(_fromUtf8("txtBoardY"))
        self.txtBoardX = QtGui.QLineEdit(self.groupBox_2)
        self.txtBoardX.setGeometry(QtCore.QRect(40, 30, 113, 33))
        self.txtBoardX.setObjectName(_fromUtf8("txtBoardX"))
        self.btnCurrentPos = QtGui.QPushButton(self.groupBox_2)
        self.btnCurrentPos.setGeometry(QtCore.QRect(10, 110, 141, 31))
        self.btnCurrentPos.setObjectName(_fromUtf8("btnCurrentPos"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.btnAddDevice = QtGui.QPushButton(self.tab_7)
        self.btnAddDevice.setGeometry(QtCore.QRect(390, 50, 95, 31))
        self.btnAddDevice.setObjectName(_fromUtf8("btnAddDevice"))
        self.btnRemoveDevice = QtGui.QPushButton(self.tab_7)
        self.btnRemoveDevice.setGeometry(QtCore.QRect(390, 90, 95, 31))
        self.btnRemoveDevice.setObjectName(_fromUtf8("btnRemoveDevice"))
        self.btnEditDevice = QtGui.QPushButton(self.tab_7)
        self.btnEditDevice.setGeometry(QtCore.QRect(390, 130, 95, 31))
        self.btnEditDevice.setObjectName(_fromUtf8("btnEditDevice"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 471))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.treeDevices = QtGui.QTreeWidget(self.tab_8)
        self.treeDevices.setGeometry(QtCore.QRect(10, 10, 351, 421))
        self.treeDevices.setColumnCount(3)
        self.treeDevices.setObjectName(_fromUtf8("treeDevices"))
        self.treeDevices.headerItem().setText(0, _fromUtf8("1"))
        self.treeDevices.headerItem().setText(1, _fromUtf8("2"))
        self.treeDevices.headerItem().setText(2, _fromUtf8("3"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_8 = QtGui.QLabel(self.tab_9)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 67, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_9)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.boxFeederType = QtGui.QComboBox(self.tab_9)
        self.boxFeederType.setGeometry(QtCore.QRect(100, 50, 131, 29))
        self.boxFeederType.setObjectName(_fromUtf8("boxFeederType"))
        self.boxFeederType.addItem(_fromUtf8(""))
        self.txtDeviceName = QtGui.QLineEdit(self.tab_9)
        self.txtDeviceName.setGeometry(QtCore.QRect(100, 10, 131, 33))
        self.txtDeviceName.setObjectName(_fromUtf8("txtDeviceName"))
        self.txtStPitch = QtGui.QLineEdit(self.tab_9)
        self.txtStPitch.setGeometry(QtCore.QRect(170, 150, 131, 33))
        self.txtStPitch.setObjectName(_fromUtf8("txtStPitch"))
        self.label_10 = QtGui.QLabel(self.tab_9)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 171, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_9)
        self.label_11.setGeometry(QtCore.QRect(50, 240, 81, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.boxStCount = QtGui.QSpinBox(self.tab_9)
        self.boxStCount.setGeometry(QtCore.QRect(170, 240, 131, 31))
        self.boxStCount.setObjectName(_fromUtf8("boxStCount"))
        self.boxStOrientation = QtGui.QComboBox(self.tab_9)
        self.boxStOrientation.setGeometry(QtCore.QRect(170, 200, 131, 29))
        self.boxStOrientation.setObjectName(_fromUtf8("boxStOrientation"))
        self.boxStOrientation.addItem(_fromUtf8(""))
        self.boxStOrientation.addItem(_fromUtf8(""))
        self.boxStOrientation.addItem(_fromUtf8(""))
        self.boxStOrientation.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(50, 200, 111, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.boxStIndex = QtGui.QSpinBox(self.tab_9)
        self.boxStIndex.setGeometry(QtCore.QRect(170, 280, 131, 31))
        self.boxStIndex.setMinimum(1)
        self.boxStIndex.setObjectName(_fromUtf8("boxStIndex"))
        self.label_13 = QtGui.QLabel(self.tab_9)
        self.label_13.setGeometry(QtCore.QRect(50, 280, 111, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.boxStVision = QtGui.QCheckBox(self.tab_9)
        self.boxStVision.setGeometry(QtCore.QRect(210, 310, 121, 26))
        self.boxStVision.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boxStVision.setObjectName(_fromUtf8("boxStVision"))
        self.label_14 = QtGui.QLabel(self.tab_9)
        self.label_14.setGeometry(QtCore.QRect(50, 340, 151, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_9)
        self.label_15.setGeometry(QtCore.QRect(50, 310, 151, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.boxStPresent = QtGui.QCheckBox(self.tab_9)
        self.boxStPresent.setGeometry(QtCore.QRect(210, 340, 121, 26))
        self.boxStPresent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boxStPresent.setObjectName(_fromUtf8("boxStPresent"))
        self.label_16 = QtGui.QLabel(self.tab_9)
        self.label_16.setGeometry(QtCore.QRect(50, 160, 111, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.btnStAlign = QtGui.QPushButton(self.tab_9)
        self.btnStAlign.setGeometry(QtCore.QRect(40, 370, 171, 31))
        self.btnStAlign.setObjectName(_fromUtf8("btnStAlign"))
        self.btnStSave = QtGui.QPushButton(self.tab_9)
        self.btnStSave.setGeometry(QtCore.QRect(240, 370, 95, 31))
        self.btnStSave.setObjectName(_fromUtf8("btnStSave"))
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.btnMoveXp = QtGui.QPushButton(self.tab_2)
        self.btnMoveXp.setGeometry(QtCore.QRect(160, 90, 20, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveXp.setFont(font)
        self.btnMoveXp.setObjectName(_fromUtf8("btnMoveXp"))
        self.btnMoveXn = QtGui.QPushButton(self.tab_2)
        self.btnMoveXn.setGeometry(QtCore.QRect(50, 90, 20, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveXn.setFont(font)
        self.btnMoveXn.setObjectName(_fromUtf8("btnMoveXn"))
        self.btnMoveYp = QtGui.QPushButton(self.tab_2)
        self.btnMoveYp.setGeometry(QtCore.QRect(90, 50, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveYp.setFont(font)
        self.btnMoveYp.setObjectName(_fromUtf8("btnMoveYp"))
        self.btnMoveYn = QtGui.QPushButton(self.tab_2)
        self.btnMoveYn.setGeometry(QtCore.QRect(90, 160, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveYn.setFont(font)
        self.btnMoveYn.setObjectName(_fromUtf8("btnMoveYn"))
        self.btnMoveXn2 = QtGui.QPushButton(self.tab_2)
        self.btnMoveXn2.setGeometry(QtCore.QRect(20, 90, 31, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveXn2.setFont(font)
        self.btnMoveXn2.setObjectName(_fromUtf8("btnMoveXn2"))
        self.btnMoveXp2 = QtGui.QPushButton(self.tab_2)
        self.btnMoveXp2.setGeometry(QtCore.QRect(180, 90, 31, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveXp2.setFont(font)
        self.btnMoveXp2.setObjectName(_fromUtf8("btnMoveXp2"))
        self.btnMoveYp2 = QtGui.QPushButton(self.tab_2)
        self.btnMoveYp2.setGeometry(QtCore.QRect(90, 20, 51, 31))
        self.btnMoveYp2.setObjectName(_fromUtf8("btnMoveYp2"))
        self.btnMoveYn2 = QtGui.QPushButton(self.tab_2)
        self.btnMoveYn2.setGeometry(QtCore.QRect(90, 180, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveYn2.setFont(font)
        self.btnMoveYn2.setObjectName(_fromUtf8("btnMoveYn2"))
        self.btnCenter = QtGui.QPushButton(self.tab_2)
        self.btnCenter.setGeometry(QtCore.QRect(99, 99, 31, 31))
        self.btnCenter.setObjectName(_fromUtf8("btnCenter"))
        self.btnHome = QtGui.QPushButton(self.tab_2)
        self.btnHome.setGeometry(QtCore.QRect(210, 10, 95, 31))
        self.btnHome.setObjectName(_fromUtf8("btnHome"))
        self.btnMoveZp = QtGui.QPushButton(self.tab_2)
        self.btnMoveZp.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.btnMoveZp.setObjectName(_fromUtf8("btnMoveZp"))
        self.btnMoveZn = QtGui.QPushButton(self.tab_2)
        self.btnMoveZn.setGeometry(QtCore.QRect(240, 113, 41, 41))
        self.btnMoveZn.setObjectName(_fromUtf8("btnMoveZn"))
        self.btnMoveRn = QtGui.QPushButton(self.tab_2)
        self.btnMoveRn.setGeometry(QtCore.QRect(210, 170, 51, 31))
        self.btnMoveRn.setObjectName(_fromUtf8("btnMoveRn"))
        self.btnMoveRp = QtGui.QPushButton(self.tab_2)
        self.btnMoveRp.setGeometry(QtCore.QRect(260, 170, 51, 31))
        self.btnMoveRp.setObjectName(_fromUtf8("btnMoveRp"))
        self.btnMoveXp1 = QtGui.QPushButton(self.tab_2)
        self.btnMoveXp1.setGeometry(QtCore.QRect(140, 90, 20, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveXp1.setFont(font)
        self.btnMoveXp1.setObjectName(_fromUtf8("btnMoveXp1"))
        self.btnMoveYp1 = QtGui.QPushButton(self.tab_2)
        self.btnMoveYp1.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveYp1.setFont(font)
        self.btnMoveYp1.setObjectName(_fromUtf8("btnMoveYp1"))
        self.btnMoveXn1 = QtGui.QPushButton(self.tab_2)
        self.btnMoveXn1.setGeometry(QtCore.QRect(70, 90, 20, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveXn1.setFont(font)
        self.btnMoveXn1.setObjectName(_fromUtf8("btnMoveXn1"))
        self.btnMoveYn1 = QtGui.QPushButton(self.tab_2)
        self.btnMoveYn1.setGeometry(QtCore.QRect(90, 140, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveYn1.setFont(font)
        self.btnMoveYn1.setObjectName(_fromUtf8("btnMoveYn1"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.btnSaveSettings = QtGui.QPushButton(self.tab_3)
        self.btnSaveSettings.setGeometry(QtCore.QRect(210, 170, 111, 31))
        self.btnSaveSettings.setObjectName(_fromUtf8("btnSaveSettings"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(550, 140, 691, 541))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.imgCCD = QtGui.QLabel(self.tab_4)
        self.imgCCD.setGeometry(QtCore.QRect(10, 30, 600, 358))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgCCD.sizePolicy().hasHeightForWidth())
        self.imgCCD.setSizePolicy(sizePolicy)
        self.imgCCD.setFrameShape(QtGui.QFrame.Box)
        self.imgCCD.setObjectName(_fromUtf8("imgCCD"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.imgCCD2 = QtGui.QLabel(self.tab_5)
        self.imgCCD2.setGeometry(QtCore.QRect(30, 10, 640, 480))
        self.imgCCD2.setFrameShape(QtGui.QFrame.Box)
        self.imgCCD2.setObjectName(_fromUtf8("imgCCD2"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.listTerminal = QtGui.QListWidget(self.centralWidget)
        self.listTerminal.setGeometry(QtCore.QRect(20, 730, 1221, 131))
        self.listTerminal.setAutoScroll(True)
        self.listTerminal.setAlternatingRowColors(True)
        self.listTerminal.setMovement(QtGui.QListView.Static)
        self.listTerminal.setFlow(QtGui.QListView.TopToBottom)
        self.listTerminal.setProperty("isWrapping", False)
        self.listTerminal.setLayoutMode(QtGui.QListView.Batched)
        self.listTerminal.setObjectName(_fromUtf8("listTerminal"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1341, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PnP test application", None))
        self.btnLoadTst.setText(_translate("MainWindow", "Load board image", None))
        self.groupBox.setTitle(_translate("MainWindow", "Origins vs geomtertic center", None))
        self.radioOrigin.setText(_translate("MainWindow", "Origins", None))
        self.radioGeometric.setText(_translate("MainWindow", "Pads geometric center", None))
        self.btnLoadPlacement.setText(_translate("MainWindow", "Load PnP Eagle data", None))
        self.btnLoadCCD.setText(_translate("MainWindow", "Take a CCD image", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "tray 1", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "tray 2", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "tray 3", None))
        self.lblAbout.setText(_translate("MainWindow", "PnP SW by Hynek Stetina\n"
"VUTBR", None))
        self.lblStatus.setText(_translate("MainWindow", "Board is not aligned!", None))
        self.label_4.setText(_translate("MainWindow", "Status:", None))
        self.txtPort.setText(_translate("MainWindow", "/dev/ttyACM0", None))
        self.btnConnect.setText(_translate("MainWindow", "Connect", None))
        self.lblMachineStatus.setText(_translate("MainWindow", "Machine is not connected", None))
        self.label_2.setText(_translate("MainWindow", "Eagle placement data", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "2", None))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "3", None))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "4", None))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "5", None))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "6", None))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "7", None))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "8", None))
        self.label_3.setText(_translate("MainWindow", "Items for placement", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "CAD data", None))
        self.btnBoardM1.setText(_translate("MainWindow", "Simple", None))
        self.btnBoardM2.setText(_translate("MainWindow", "Semiautomatic", None))
        self.btnBoardM3.setText(_translate("MainWindow", "Fully automatic", None))
        self.btnClearAlignment.setText(_translate("MainWindow", "Clear Alignment", None))
        self.label_7.setText(_translate("MainWindow", "Status:", None))
        self.btnAlign.setText(_translate("MainWindow", "Align procedure", None))
        self.lblO1.setText(_translate("MainWindow", "TextLabel", None))
        self.lblO2.setText(_translate("MainWindow", "TextLabel", None))
        self.lblO3.setText(_translate("MainWindow", "TextLabel", None))
        self.lblP1.setText(_translate("MainWindow", "TextLabel", None))
        self.lblP2.setText(_translate("MainWindow", "TextLabel", None))
        self.lblP3.setText(_translate("MainWindow", "TextLabel", None))
        self.lblBoardStatus.setText(_translate("MainWindow", "Board is not aligned!", None))
        self.imgFiduc1.setText(_translate("MainWindow", "imgFiduc1", None))
        self.imgFiduc2.setText(_translate("MainWindow", "imgFiduc2", None))
        self.imgFiduc3.setText(_translate("MainWindow", "imgFiduc3", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Board offset", None))
        self.label_5.setText(_translate("MainWindow", "X:", None))
        self.label_6.setText(_translate("MainWindow", "Y:", None))
        self.btnCurrentPos.setText(_translate("MainWindow", "Get current position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Board alignment", None))
        self.btnAddDevice.setText(_translate("MainWindow", "Add", None))
        self.btnRemoveDevice.setText(_translate("MainWindow", "Remove", None))
        self.btnEditDevice.setText(_translate("MainWindow", "Edit", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Devices", None))
        self.label_8.setText(_translate("MainWindow", "Name:", None))
        self.label_9.setText(_translate("MainWindow", "Feeder type:", None))
        self.boxFeederType.setItemText(0, _translate("MainWindow", "Static tape", None))
        self.label_10.setText(_translate("MainWindow", "Static tape alignment:", None))
        self.label_11.setText(_translate("MainWindow", "Part count:", None))
        self.boxStOrientation.setItemText(0, _translate("MainWindow", "X+", None))
        self.boxStOrientation.setItemText(1, _translate("MainWindow", "X-", None))
        self.boxStOrientation.setItemText(2, _translate("MainWindow", "Y+", None))
        self.boxStOrientation.setItemText(3, _translate("MainWindow", "Y-", None))
        self.label_12.setText(_translate("MainWindow", "Tape orientation:", None))
        self.label_13.setText(_translate("MainWindow", "Current index:", None))
        self.boxStVision.setText(_translate("MainWindow", "hhh", None))
        self.label_14.setText(_translate("MainWindow", "V: part present check:", None))
        self.label_15.setText(_translate("MainWindow", "Use vision (slow):", None))
        self.boxStPresent.setText(_translate("MainWindow", "zzz", None))
        self.label_16.setText(_translate("MainWindow", "Part pitch:", None))
        self.btnStAlign.setText(_translate("MainWindow", "Align 1st part position", None))
        self.btnStSave.setText(_translate("MainWindow", "Save", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Properties", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Device manager", None))
        self.btnMoveXp.setText(_translate("MainWindow", "→", None))
        self.btnMoveXn.setText(_translate("MainWindow", "←", None))
        self.btnMoveYp.setText(_translate("MainWindow", "↑", None))
        self.btnMoveYn.setText(_translate("MainWindow", "↓", None))
        self.btnMoveXn2.setText(_translate("MainWindow", "⇇", None))
        self.btnMoveXp2.setText(_translate("MainWindow", "⇉", None))
        self.btnMoveYp2.setText(_translate("MainWindow", "⇈", None))
        self.btnMoveYn2.setText(_translate("MainWindow", "⇊", None))
        self.btnCenter.setText(_translate("MainWindow", "0", None))
        self.btnHome.setText(_translate("MainWindow", "Home all", None))
        self.btnMoveZp.setText(_translate("MainWindow", "Z ↑", None))
        self.btnMoveZn.setText(_translate("MainWindow", "Z ↓", None))
        self.btnMoveRn.setText(_translate("MainWindow", "↶ R", None))
        self.btnMoveRp.setText(_translate("MainWindow", "R ↷", None))
        self.btnMoveXp1.setText(_translate("MainWindow", "→", None))
        self.btnMoveYp1.setText(_translate("MainWindow", "↑", None))
        self.btnMoveXn1.setText(_translate("MainWindow", "←", None))
        self.btnMoveYn1.setText(_translate("MainWindow", "↓", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Motion", None))
        self.btnSaveSettings.setText(_translate("MainWindow", "Apply settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings", None))
        self.label.setText(_translate("MainWindow", "Placement simulator", None))
        self.imgCCD.setText(_translate("MainWindow", "Simulation image", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Simulation", None))
        self.imgCCD2.setText(_translate("MainWindow", "Real CCD image", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "CCD", None))
        self.listTerminal.setSortingEnabled(False)

